export const locations : { position: [number, number]; name: string; description: string; number: string }[] = [
    {
      name: "Winget",
      position: [9.0417, 38.7464],
      description: "Residential area near the Addis Ababa University College of Natural Sciences and the Winget Botanical Garden",
      number: "+5",
    },
    {
      name: "Entoto",
      position: [9.0667, 38.8],
      description: "Mountainous area north of Addis containing the Entoto Natural Park, historic churches, and panoramic city views",
      number: "+10",
    },
    {
      name: "LomiMeda",
      position: [9.0167, 38.7167],
      description: "Western neighborhood near the Ethiopian National Theater and Addis Ababa City Hall",
      number: "+5",
    },
    {
      name: "St Pawlos",
      position: [9.0333, 38.75],
      description: "Historic district home to St. Paul's Hospital and near the Piazza government district",
      number: "+15",
    },
    {
      name: "Shiro Meda",
      position: [9.016, 38.77],
      description: "Traditional textile market area at the foothills of Entoto, known for Ethiopian cultural clothing",
      number: "+20",
    },
    {
      name: "Pastor",
      position: [8.9833, 38.8],
      description: "Affluent Bole district area near Bole International Airport and international embassies",
      number: "+15",
    },
    {
      name: "Enkulala Fabrica",
      position: [9.0333, 38.7167],
      description: "Industrial area in western Addis near the Ethiopian Railway Corporation headquarters",
      number: "15",
    },
    {
      name: "Mesalemiya",
      position: [8.8833, 38.7833],
      description: "Southern industrial zone containing manufacturing plants and the Akaki Railway Station",
      number: "+10",
    },
    {
      name: "Giorgis",
      position: [9.0189, 38.7613],
      description: "Central square surrounding the iconic St. George's Cathedral and museum",
      number: "+10",
    },
    {
      name: "18 Mazoriya",
      position: [9.0385, 38.7584],
      description: "Area near the National Museum of Ethiopia which houses the Lucy fossil remains",
      number: "+20",
    },
    {
      name: "Merkato",
      position: [9.0364, 38.7523],
      description: "Africa's largest open-air market sprawling across several city blocks in the Arada district",
      number: "+25",
    },
    {
      name: "Piyasa",
      position: [8.9779, 38.7993],
      description: "Commercial hub near Bole Airport with numerous shops, hotels and the Friendship City Park",
      number: "+20",
    },
    {
      name: "Abinet",
      position: [9.0444, 38.7595],
      description: "Area surrounding Addis Ababa University's main campus and the Ethiopian National Library",
      number: "+10",
    },
    {
      name: "English Embassay",
      position: [9.1167, 38.8167],
      description: "Diplomatic enclave in the highland area of Entoto, near the British Ambassador's residence",
      number: "+15",
    },
    {
      name: "Kotebe",
      position: [9.0167, 38.7333],
      description: "Location of Kotebe University of Education and residential neighborhoods in eastern Addis",
      number: "+10",
    },
    {
      name: "Kazanchis",
      position: [8.9964, 38.7867],
      description: "Business district housing the United Nations Economic Commission for Africa headquarters",
      number: "+25",
    },
    {
      name: "Arat Kilo",
      position: [9.0336, 38.76],
      description: "Major intersection and historic square near Addis Ababa University and the Parliament building",
      number: "+30",
    },
    {
      name: "Mexico",
      position: [9.0369, 38.7564],
      description: "Central area named after the Mexican embassy, near the Hilton Hotel and Holy Trinity Cathedral",
      number: "+30",
    },
    {
      name: "Alem Bank",
      position: [9.0833, 38.8167],
      description: "Northern area near Entoto Maryam Church and the former Alem Bank headquarters",
      number: "+25",
    },
    {
      name: "Tor Hayloch",
      position: [9.0278, 38.7508],
      description: "Post office square area connecting Churchill Avenue to the Mercato district",
      number: "+25",
    },
    {
      name: "Legehar",
      position: [9.0342, 38.7639],
      description: "Area near the British Embassy and the African Union Conference Center",
      number: "+15",
    },
    {
      name: "Sarbet",
      position: [9.0167, 38.8],
      description: "Northern traffic circle connecting Bole Road to the Entoto hills",
      number: "+15",
    },
    {
      name: "Meskel flower",
      position: [8.95, 38.7667],
      description: "Southern industrial area near the Kaliti prison and Meskel Flower factory",
      number: "+25",
    },
    {
      name: "Gerji",
      position: [9.0167, 38.8167],
      description: "Upper middle-class residential area near Bole with shopping plazas and restaurants",
      number: "+25",
    },
    {
      name: "Jemo",
      position: [9.0, 38.7833],
      description: "Residential high-rise area near Bole with the Jemo shopping mall and new condominiums",
      number: "+10",
    },
    {
      name: "Haile Garment",
      position: [8.9833, 38.7833],
      description: "Industrial zone in the Bole area containing textile factories including Haile Garment",
      number: "+20",
    },
    {
      name: "Lebu",
      position: [8.9833, 38.8167],
      description: "Area near Bole Airport with the Lebu amusement park and numerous international hotels",
      number: "+15",
    },
    {
      name: "Gelan",
      position: [8.8333, 38.8167],
      description: "Southern industrial expansion area along the new expressway to Adama",
      number: "+5",
    },
    {
      name: "Tulu Dimtu",
      position: [9.0667, 38.7667],
      description: "Eastern residential neighborhood near the Ethiopian Civil Service University",
      number: "+10",
    },
    {
      name: "Saris",
      position: [9.0333, 38.8333],
      description: "Northern suburb known for Saris Abo mineral water source and recreational areas",
      number: "+10",
    },
    {
      name: "Abo (Saris Abo)",
      position: [9.0417, 38.8417],
      description: "Natural spring water source area in northern Addis, popular for picnics and holy water collection",
      number: "3",
    },
    {
      name: "Bole Michael",
      position: [9.0, 38.7667],
      description: "Commercial hub in Bole district near Edna Mall and numerous international restaurants",
      number: "+",
    },
    {
      name: "Megenagna",
      position: [9.0, 38.7667],
      description: "Major intersection and business district connecting Bole to CMC and other eastern areas",
      number: "+25",
    },
    {
      name: "CMC",
      position: [9.0, 38.7667],
      description: "Area near the Ethiopian Commodity Exchange and the Commercial Bank of Ethiopia headquarters",
      number: "+10",
    },
    {
      name: "Semit",
      position: [9.0, 38.7667],
      description: "Residential area near the Semien Hotel and the Ethiopian Roads Authority offices",
      number: "+10",
    }
  ];